name: Code Quality

on:
  pull_request:
    branch:
      - main
      - dev

jobs:
  check-project-doc:
    timeout-minutes: 3
    name: test project document quality
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: ./docs/project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        uses: bun install
      - name: Check format
        uses: bun run format:check
      - name: Check type
        uses: bun run typecheck

  action-timeline:
    needs: [check-project-doc]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2