name: Test Build

on:
  pull_request:
    branches:
      - dev

jobs:
  test-build-project-doc:
    timeout-minutes: 3
    name: build a project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run build

  test-build-top-page-doc:
    timeout-minutes: 1
    name: build a top page
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/top-page
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run build

  test-native-back-end-api-doc:
    timeout-minutes: 3
    name: build the native back end app api doc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo doc --all --no-deps --document-private-items

  action-timeline:
    needs: [test-build-project-doc, test-build-top-page-doc, test-native-back-end-api-doc]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2